import { Canvas, extend, useFrame, useThree } from '@react-three/fiber';
import React, { useRef } from 'react';
import '../styles/globals.css';
import type { AppProps } from 'next/app';
import Head from 'next/head';
import { OrbitControls } from '@react-three/drei';

function MyApp({ Component, pageProps }: AppProps) {
    return (
        <div
            style={{
                position: 'absolute',
                width: '100%',
                height: '100%',
                left: '0',
                right: '0',
                top: '0',
                bottom: '0',
            }}>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Canvas
                camera={{
                    fov: 60,
                    near: 0.1,
                    far: 1000,
                    position: [0, 2, 2.4],
                    rotation: [0, 0, 0],
                }}
                resize={{ scroll: true, debounce: { scroll: 50, resize: 0 } }}>
                <OrbitControls />
                <Component {...pageProps} />
            </Canvas>
        </div>
    );
}

export default MyApp;
